name = "segc_wl"
uuid = "ce517a80-2c89-4871-b5a9-77267e0ac583"
version = "0.1.0"
authors = ["McKinleyPaul <mkpaulx@gmail.com>"]

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
JLD2 = "0.6.3"
Printf = "1.11.0"
Random = "1.11.0"
StaticArrays = "1.9.15"
